"""Fixed sequences and public defaults for the probe designer."""

from __future__ import annotations

PROBE_L_ADAPTOR = "CTCTATGGGCAGTCGGTGATATCGACCTGTACCTCT"
PROBE_R_ADAPTOR = "CCATCTCATCCCTGCGTGTCCATCATCCGTACGTGT"

UNIVERSAL_PRIMER_F = "CCATCTCATCCCTGCGTGTC"
UNIVERSAL_PRIMER_R = "AGAGGTACAGGTCGATATCA"

SPLIT_MODE_OXIDIZED_TO_R = "oxidized_base_belongs_to_R"
SPLIT_MODE_OXIDIZED_TO_L = "oxidized_base_belongs_to_L"

SUPPORTED_SPLIT_MODES = (
    SPLIT_MODE_OXIDIZED_TO_R,
    SPLIT_MODE_OXIDIZED_TO_L,
)

SPLIT_MODE_DESCRIPTIONS = {
    SPLIT_MODE_OXIDIZED_TO_R: "Oxidized base belongs to Probe R",
    SPLIT_MODE_OXIDIZED_TO_L: "Oxidized base belongs to Probe L",
}

DEFAULT_SPLIT_MODE = SPLIT_MODE_OXIDIZED_TO_R
DEFAULT_ADD_PROBE_L_PHOSPHATE_TAG = True
DEFAULT_FORMAT_PROBE_R_LAST_TWO_AS_RNA = True

LIGATED_PRODUCT_ORIENTATION = "5' - Probe R - Probe L - 3'"
